"""add photo_file_name to wish

Revision ID: d1fc68ca6464
Revises: 669b3e235115
Create Date: 2026-06-25 11:29:31.184313

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d1fc68ca6464"
down_revision: Union[str, Sequence[str], None] = "669b3e235115"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("wish", sa.Column("photo_file_name", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("wish", "photo_file_name")
    # ### end Alembic commands ###
