"""initial

Revision ID: 669b3e235115
Revises:
Create Date: 2026-06-25 10:04:48.359899

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "669b3e235115"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
